# Generated by Django 4.0.2 on 2022-02-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='retal_price_day',
            new_name='rental_price_day',
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(blank=True, choices=[('avaliable', 'avaliable'), ('rental', 'rental'), ('sold', 'sold')], max_length=50, null=True),
        ),
    ]
