# Generated by Django 4.0.2 on 2022-02-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary_app', '0002_rename_retal_price_day_book_rental_price_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
